/// <reference path="react/react.d.ts" />
/// <reference path="react/react-dom.d.ts" />
/// <reference path="react-mixin/react-mixin.d.ts" />
/// <reference path="fastclick/fastclick.d.ts" />
/// <reference path="classnames/classnames.d.ts" />
/// <reference path="node/node.d.ts" />
/// <reference path="modernizr/modernizr.d.ts" />
/// <reference path="react-router/history.d.ts" />
/// <reference path="react-router/react-router.d.ts" />
/// <reference path="redux/redux.d.ts" />
/// <reference path="react-redux/react-redux.d.ts" />
/// <reference path="redux-actions/redux-actions.d.ts" />
/// <reference path="redux-logger/redux-logger.d.ts" />
/// <reference path="whatwg-fetch/whatwg-fetch.d.ts" />
/// <reference path="redux-thunk/redux-thunk.d.ts" />
/// <reference path="react-motion/react-motion.d.ts" />
/// <reference path="react-router-redux/react-router-redux.d.ts" />
/// <reference path="source-map/source-map.d.ts" />
/// <reference path="uglify-js/uglify-js.d.ts" />
/// <reference path="webpack/webpack.d.ts" />
// <reference path="core-js/core-js.d.ts" />

declare var __CLIENT__: boolean;
declare var __SERVER__: boolean;
declare var __DEVELOPMENT__: boolean;
